### ISSUE TITLE
Use this lib in qnx system.

### ISSUE THREAD

**Issue by QianWenxiang** [luuhuuquyet/OpenCV-3.2-QNX700#1]
Hi, bro,could you help me to look look, I just use waitkey interface,but meet this error, I don't know how to fix, please help help me , thanks you! 

OpenCV Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvWaitKey, file /home/quyetluu/build_opencv/opencv-3.2.0/modules/highgui/src/window.cpp, line 654
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/quyetluu/build_opencv/opencv-3.2.0/modules/highgui/src/window.cpp:654: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvWaitKey

**Comment by luuhuuquyet** [comment]
Hi,
I am not sure, but I think you can workaround by using another methods to read the input from keyboard. Example some standard libraries in C/C++ getc or cin.

**Comment by QianWenxiang** [comment]
ok, thanks your lib and reply!  :)
