### ISSUE TITLE
A Brief Explanation of Compilation Process

### ISSUE THREAD

**Issue by MK97w** [luuhuuquyet/OpenCV-3.2-QNX700#2]
Hey. I was also working on QNX7 and trying to port opencv(most likely to use version 3.1). I am using aarch64le target and x86_x64 windows host. I am using CMake Gui to configure and generate. But after generation what should i do in order to  obtain the lib and includes ?

Can you give a brief explanation about the steps you took to compile those files?

Also my question is not directly related with the topic but, this was the only valid resource about qnx7 and opencv (v3+ ) that i could find on the internet. I would appreciate any type of help.

**Comment by luuhuuquyet** [comment]
Hi,
I am sorry for my late reply. I think you should do some revise for the building. 
Please get some information here for your references:
https://drive.google.com/file/d/1KVRR-8vZVUecw15CsRciGl9C5wsKkS6i/view?usp=sharing
I hope it can help you :)
